version: '3'
services:
    wordpress:
        build: docker/wordpress
        depends_on:
            - db
        restart: unless-stopped
        volumes:
            - ./html:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_PASSWORD: p4ssw0rd!
        ports:
            - 80:80
            - 443:443
        networks:
            - back
    db:
        build: docker/mysql
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: p4ssw0rd!
        networks:
            - back
    phpmyadmin:
        build: docker/phpmyadmin
        depends_on:
            - db
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: p4ssw0rd!
        networks:
            - back
networks:
    back:
volumes:
    db_data: