version: '3'
services:
    wordpress:
        build: docker/wordpress
        depends_on:
            - db
        restart: always
        volumes:
            - ./wp-content:/var/www/html/wp-content            
        ports:
            - 80:80
            - 443:443
        networks:
            - back
    db:
        build: docker/mysql
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - back
    phpmyadmin:
        build: docker/phpmyadmin
        depends_on:
            - db
        restart: always
        ports:
            - 8080:80
        networks:
            - back
networks:
    back:
volumes:
    db_data: